version: '3.5'
services:
  apache:
    container_name: wolpertinger-apache
    image: httpd
    ports:
    - 80:80
    volumes:
    - ./images:/usr/local/apache2/htdocs/images/
networks:
  default:
    name: wolpertinger